import os
from datetime import datetime
import replicate

MODEL_NAME = "anthropic/claude-4-sonnet"


def clean_value(value, default="N/A"):
    if value is None or value == "":
        return default
    return value


def generate_thyroid_report(data: dict) -> dict:
    today = datetime.now().strftime("%B %d, %Y")

    patient_name = clean_value(data.get("patient_name"))
    patient_id = clean_value(data.get("patient_id"))
    age = clean_value(data.get("age"))
    gender = clean_value(data.get("gender"))
    diagnosis_date = clean_value(data.get("date_of_diagnosis"))

    lobe_involvement = clean_value(data.get("lobe_involvement"))
    tumor_size = clean_value(data.get("tumor_size_cm"))
    num_nodules = clean_value(data.get("number_of_nodules"))

    composition = clean_value(data.get("composition"))
    echogenicity = clean_value(data.get("echogenicity"))
    shape = clean_value(data.get("shape"))
    margin = clean_value(data.get("margin"))
    ti_rads = clean_value(data.get("ti_rads_score"))

    cancer_type = clean_value(data.get("cancer_type"))

    pathological_features = data.get("pathological_features", [])
    features_str = ", ".join(pathological_features) if pathological_features else "None reported"

    t_stage = clean_value(data.get("t_stage"))
    n_stage = clean_value(data.get("n_stage"))
    m_stage = clean_value(data.get("m_stage"))
    stage_group = clean_value(data.get("stage_group"))
    ata_risk = clean_value(data.get("ata_risk"))

    metastasis_sites = data.get("metastasis_sites", [])
    metastasis_str = ", ".join(metastasis_sites) if metastasis_sites else "None"

    braf_v600e = clean_value(data.get("braf_v600e"), "Not tested")
    ras_mutation = clean_value(data.get("ras_mutation"), "Not tested")
    ret_ptc = clean_value(data.get("ret_ptc"), "Not tested")
    tert = clean_value(data.get("tert_promoter"), "Not tested")

    tg = clean_value(data.get("tg_thyroglobulin"))
    anti_tg = clean_value(data.get("anti_tg_antibodies"))
    calcitonin = clean_value(data.get("calcitonin"))

    surgery = clean_value(data.get("surgery_type"))
    rai_dose = clean_value(data.get("rai_dose"))
    date_of_rai = clean_value(data.get("date_of_rai"))
    levothyroxine = clean_value(data.get("levothyroxine_dose"))
    next_visit = clean_value(data.get("next_visit"))
    next_tg_check = clean_value(data.get("next_tg_check"))

    prompt = f"""
You are a clinical thyroid cancer reporting assistant for Diagnovate Clinical Platform.

Generate a professional thyroid cancer medical report based ONLY on the doctor-entered data below.

IMPORTANT ACCURACY RULES:
- Do NOT invent symptoms, findings, treatments, metastasis, molecular results, or recommendations that are not supported by the provided data.
- Do NOT say a result is positive, negative, or present unless it is explicitly provided.
- If a field is N/A, Not tested, None, or missing, mention it as not provided only when clinically relevant.
- Be conservative and medically accurate.
- Keep the report concise, formal, and PDF-ready.
- Use clear Markdown headings.
- Do NOT write "[Current Date]". Use this exact report date: {today}.
- End the report with a separated footer containing Report Generated by, Platform, and Date of Report each on its own line.

=== PATIENT INFORMATION ===
Name: {patient_name}
ID: {patient_id}
Age: {age}
Gender: {gender}
Date of Diagnosis: {diagnosis_date}

=== PRIMARY TUMOR CHARACTERISTICS ===
Lobe Involvement: {lobe_involvement}
Tumor Size: {tumor_size} cm
Number of Nodules: {num_nodules}

=== ULTRASOUND FEATURES ===
Composition: {composition}
Echogenicity: {echogenicity}
Shape: {shape}
Margin: {margin}
TI-RADS Score: {ti_rads}

=== HISTOPATHOLOGICAL TYPE ===
Cancer Type: {cancer_type}

=== PATHOLOGICAL FEATURES ===
{features_str}

=== TNM STAGING (AJCC 8th Edition) ===
T Stage: {t_stage}
N Stage: {n_stage}
M Stage: {m_stage}
Stage Group: {stage_group}
ATA Risk: {ata_risk}
Metastasis Sites: {metastasis_str}

=== MOLECULAR MARKERS ===
BRAF V600E: {braf_v600e}
RAS Mutation: {ras_mutation}
RET/PTC: {ret_ptc}
TERT Promoter: {tert}

=== SERUM MARKERS ===
TG (Thyroglobulin): {tg} ng/mL
Anti-TG Antibodies: {anti_tg} IU/mL
Calcitonin: {calcitonin} pg/mL

=== TREATMENT ===
Surgery Procedure: {surgery}
RAI Dose: {rai_dose} mCi
Date of RAI: {date_of_rai}
Levothyroxine Dose: {levothyroxine} mcg/day

=== FOLLOW-UP PLAN ===
Next Visit: {next_visit}
Next TG Check: {next_tg_check}

Return the report using exactly this structure:

# THYROID CANCER MEDICAL REPORT

## PATIENT SUMMARY
Paragraph here.

## CLINICAL PRESENTATION & IMAGING FINDINGS
Paragraph here.

## HISTOPATHOLOGICAL DIAGNOSIS
Paragraph here.

## PATHOLOGICAL FEATURES
Paragraph here.

## MOLECULAR PROFILE & GENETIC MARKERS
Paragraph here.

## SERUM TUMOR MARKERS
Paragraph here.

## TNM STAGING & RISK STRATIFICATION
Paragraph here.

## TREATMENT PLAN & INTERVENTIONS
Paragraph here.

## FOLLOW-UP PROTOCOL
Paragraph here.

## PHYSICIAN'S SUMMARY & RECOMMENDATIONS
Paragraph here.

---

Report Generated by: Senior Oncology Physician Assistant
Platform: Diagnovate Clinical Platform
Date of Report: {today}
"""

    output = replicate.run(
        MODEL_NAME,
        input={"prompt": prompt}
    )

    if isinstance(output, list):
        report_text = "".join(str(item) for item in output)
    else:
        report_text = str(output)

    return {
        "patient_name": patient_name,
        "patient_id": patient_id,
        "diagnosis_date": diagnosis_date,
        "cancer_type": cancer_type,
        "stage_group": stage_group,
        "ata_risk": ata_risk,
        "report_text": report_text,
        "model_used": MODEL_NAME
    }